version: '3.8'

services:
  tsc:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes: 
      - "files:/tsc/"
      - ./requirements.txt:/tsc/requirements.txt

volumes:
  files: